### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by eoovipaul** [bbc/sqs-producer#21]
Have it all set up and suddenly got a cb is not a function TypeError. Please see code below

`E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

TypeError: cb is not a function
    at Producer._sendBatch (E:\Platform\OBSIDIAN\node_modules\sqs-producer\lib\producer.js:133:5)
    at Producer.send (E:\Platform\OBSIDIAN\node_modules\sqs-producer\lib\producer.js:158:8)
    at Response.sqs.getQueueUrl (E:\Platform\OBSIDIAN\application\routes\upload.js:75:34)
    at Request.<anonymous> (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:364:18)
    at Request.callListeners (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Request.emit (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Request.emit (E:\Platform\OBSIDIAN\node_modules\aws-sdk\lib\sequential_executor.js:77:10)`

**Comment by nspragg** [comment]
I suggest you check the method signature of the call you're making and ensure you're passing a function
